### ISSUE TITLE
Error with Assimp32.dll

### ISSUE THREAD

**Issue by LAUROZZ** [RenolY2/SuperBMD#11]
I get this error but I have Assimp32.dll placed inside the folder, any solution?
```
Unhandled Exception: Assimp.AssimpException: Error loading unmanaged library from path: Assimp32.dll, see inner exception for details.
The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   --- End of inner exception stack trace ---
   at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
   at Assimp.AssimpContext.CreateConfigs()
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   at SuperBMD.Model.Load(String filePath, List`1 mat_presets, TristripOption triopt, Boolean flipAxis, Boolean fixNormals, String additionalTexPath)
   at SuperBMD_UnitTest.Program.Main(String[] args)
```

**Comment by RenolY2** [comment]
The error is a bit misleading because what it's actually not finding is the dlls that Assimp32.dll depends on. Specifically, msvcp110.dll and msvcr110.dll

I added those dlls in the new compiled release: https://github.com/RenolY2/SuperBMD/releases/tag/v1.3.5 I hope that helps

**Comment by LAUROZZ** [comment]
Yes, it works now, thanks for do it, it is a really nice program :D

**Comment by RenolY2** [comment]
I'm glad you like it :)
Good to know that this fixed it for you.
