### ISSUE TITLE
Won't convert models with armatures

### ISSUE THREAD

**Issue by aconeishone** [RenolY2/SuperBMD#38]
Says this whenever I try to convert a model with an armature

Searching for the Skeleton RootFound skeleton root: kosinull
Found skeleton root: rhandjnt

Unhandled Exception: System.Exception: Cannot convert model: Found more than one root bone: kosinull, rhandjnt
   at SuperBMDLib.BMD.JNT1.GetRootBone(Scene scene)
   at SuperBMDLib.Model..ctor(Scene scene, Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Program.Main(String[] args)
   
   Which makes no sense because it also fails to so when using a model directly from pikmin 2 itself

**Comment by RenolY2** [comment]
I released a new version that should fix this:
https://github.com/RenolY2/SuperBMD/releases/tag/v2.4.0.1

**Comment by aconeishone** [comment]
> I released a new version that should fix this: https://github.com/RenolY2/SuperBMD/releases/tag/v2.4.0.1

Thanks, but now it gives me this error instead
```SuperBMD v2.4.0.1

Preparing to convert oildumple from .FBX to .BMD

Sorting Meshes.......√

Searching for the Skeleton Rootago
body
head
regL_momo
regL_sune
regR_momo
regR_sune
Found skeleton root candidate: regR_momo
Found skeleton root candidate: regL_momo

Unhandled Exception: System.Exception: Cannot convert model: Found more than one root bone: regR_momo, regL_momo
   at SuperBMDLib.BMD.JNT1.GetRootBone(Scene scene)
   at SuperBMDLib.Model..ctor(Scene scene, Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Program.Main(String[] args)
```

**Comment by RenolY2** [comment]
Can you send me that fbx?

**Comment by aconeishone** [comment]
> Can you send me that fbx?

Okay, how do you want me to send it to you? Also I got the fbx from converting pikmin 2's models into glb using finmodelutilites, then I modified the texture in blender and exported it as an fbx

**Comment by RenolY2** [comment]
You can compress it into a zip file and then upload the zip in a comment here.

**Comment by aconeishone** [comment]
[New folder (4).zip](https://github.com/RenolY2/SuperBMD/files/9803657/New.folder.4.zip)
alright here it is

**Comment by aconeishone** [comment]
ok nice
