### ISSUE TITLE
error converting dae to bmd

### ISSUE THREAD

**Issue by aconeishone** [RenolY2/SuperBMD#39]
when I try to convert my dae to a bmd it gives me this error

```
SuperBMD v2.4.0.0

Preparing to convert coneabomination from .DAE to .BMD

Sorting Meshes....
Unhandled Exception: System.Exception: Number of meshes (2) is not the same as the number of mesh objects (0); cannot sort.
Mesh objects:
Meshes: Mesh_0, Mesh_0
   at SuperBMDLib.Model.SortMeshesByObjectNames(Scene scene)
   at SuperBMDLib.Model..ctor(Scene scene, Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Program.Main(String[] args)
```

what do I do about this?

**Comment by RenolY2** [comment]
Use ``--no_sort`` argument when calling superbmd (or add it to the .bat) or try the newer version where it won't throw an error anymore when it can't sort meshes: https://github.com/RenolY2/SuperBMD/releases/tag/v2.4.0.1
